services:
  app:
    build:
      tags:
        - db-backuper:dev
      context: .
      dockerfile: .deploy/Dockerfile
    ports:
      - "${APP_PORT:-9033}:80"
    env_file:
      - .env
    volumes:
      - '.:/var/www/html'
